#!/bin/bash
#
# name     : monbar, status bar for monsterwm
# modified : 2013 Jan 29
#

ff="/tmp/monsterwm.fifo"
[[ -p $ff ]] || mkfifo -m 600 "$ff"

# desktop names
ds=("º dev" "© www" "¦ gfx" "Ï etc")

# layout names
ms=("þ" "û" "ü" "ú" "ý")

while read -t 1 -r wmout || true; do
  if [[ $wmout =~ ^(([[:digit:]]+:)+[[:digit:]]+ ?)+$ ]]; then
    read -ra desktops <<< "$wmout" && unset r
    for desktop in "${desktops[@]}"; do
      IFS=':' read -r d w m c u <<< "$desktop"
      ((c)) && fg="\\f7" i="${ms[$m]}" || fg="\\f9"
      #((u)) && w+='\f5!'
      #r+="$fg${ds[$d]} ${w/#0/\\f6-} \\f9:: "
      r+="$fg${ds[$d]} \\f9 "
    done
    r="${r%*}"
  fi
  printf "\\\l%s\\\r%s\n" "$r\\f4$i" "\\f8ê \\f3$(nowplaying) \\f8Ñ \\f4$(cpu) \\f8Æ \\f4$(mem) \\f8Ý \\f7$(net down) \\f8Ü \\f7$(net) \\f8­ \\f7$(wifi) \\f8Ì \\f5$(gmail) \\f8ð \\f5$(batter) \\f8í \\f5$(volume) \\f8· \\f1$(date +"%a, %b %d \\f8/ \\f1%R")"
done < "$ff" | bar &

# pass output to pipe and print to stdout
monsterwm > "$ff"
