#!/usr/bin/env ruby
#
# name     : net, network information for mobar
# author   : Xu Xiaodong <xxdlhy@gmail.com>
# license  : GPL
# created  : 2012 Jul 31
# modified : 2012 Sep 26
#

def process_exist? cmd
  pid = %x(pidof #{cmd})
  pid.empty? ? false : true
end

def parse file
  File.open(file) { |f| f.readline.to_i }
end

wpa = process_exist? 'wpa_supplicant'
net = wpa ? 'wlan' : 'eth'

prev_rx_bytes = parse "/sys/class/net/#{net}0/statistics/rx_bytes"
prev_tx_bytes = parse "/sys/class/net/#{net}0/statistics/tx_bytes"

sleep 1

cur_rx_bytes = parse "/sys/class/net/#{net}0/statistics/rx_bytes"
cur_tx_bytes = parse "/sys/class/net/#{net}0/statistics/tx_bytes"

rx = ((cur_rx_bytes - prev_rx_bytes).to_f / 1024).to_i
tx = ((cur_tx_bytes - prev_tx_bytes).to_f / 1024).to_i

if ARGV.shift == 'down'
  puts "#{rx}KB/s"
else
  puts "#{tx}KB/s"
end
